### ISSUE TITLE
Permission denied for mkdir

### ISSUE THREAD

**Issue by sysoppl** [timvisee/send#17]
After creating docker container with this config:

```
sudo docker create --name send \
  -e 'NODE_ENV=production' \
  -e 'PORT=127.0.0.1:1234:1443' \
  -e 'REDIS_HOST=1.2.3.4' \
  -e 'BASE_URL=https://url.com' \
  -e 'FILE_DIR=/mnt/hdd/ffsend/' \
  -e 'MAX_FILE_SIZE=10737420000' \
  -e 'MAX_EXPIRE_SECONDS=604800' \
  registry.gitlab.com/timvisee/send:latest && sudo docker start send
```
it shows this error:

```
{"Timestamp":1618045757728000000,"Logger":"FirefoxSend","Type":"uncaughtException","Severity":0,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"Error: EACCES: permission denied, mkdir '/mnt/hdd'","stack":"\n    at Object.mkdirSync (node:fs:1010:3)\n    at sync (/app/node_modules/mkdirp/index.js:72:13)\n    at sync (/app/node_modules/mkdirp/index.js:78:24)\n    at Function.sync (/app/node_modules/mkdirp/index.js:78:24)\n    at new FSStorage (/app/server/storage/fs.js:12:12)\n    at new DB (/app/server/storage/index.js:22:20)\n    at Object.<anonymous> (/app/server/storage/index.js:86:18)\n    at Module._compile (node:internal/modules/cjs/loader:1108:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n    at Module.load (node:internal/modules/cjs/loader:973:32)"}}
```
It won't create this folder.
I tried creating it manually - nothing / added permissions - nothing. 
Many other containers had no problem creating folders in this path 
Any ideas / help?

**Comment by timvisee** [comment]
This likely happens because the container uses a special user (to prevent running as root). Because of this, I don't think the container user has permission to the directory.

Would you mind to temporarily change the directory permission to 777, to test whether the error still comes up when everyone is allowed?

```bash
chmod -R 777 /mnt/hdd/ffsend
```

Note that this permission setting is considered insecure, and is just used for testing purposes here.

**Comment by sysoppl** [comment]
Yes, changed permissions:
![obraz](https://user-images.githubusercontent.com/30871217/114413073-f52dd080-9bad-11eb-9789-80a4e8763087.png)
and recreated docker. Same error
```
{"Timestamp":1618238514711000000,"Logger":"FirefoxSend","Type":"uncaughtException","Severity":0,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"Error: EACCES: permission denied, mkdir '/mnt/hdd'","stack":"\n    at Object.mkdirSync (node:fs:1010:3)\n    at sync (/app/node_modules/mkdirp/index.js:72:13)\n    at Function.sync (/app/node_modules/mkdirp/index.js:78:24)\n    at new FSStorage (/app/server/storage/fs.js:12:12)\n    at new DB (/app/server/storage/index.js:22:20)\n    at Object.<anonymous> (/app/server/storage/index.js:86:18)\n    at Module._compile (node:internal/modules/cjs/loader:1108:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n    at Module.load (node:internal/modules/cjs/loader:973:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:813:14)"}}
```

**Comment by timvisee** [comment]
Took another look at your command. It looks like you're missing a mount argument for the container.

`-e 'FILE_DIR=/mnt/hdd/ffsend/'` just tells Send in the container where to place files (from within the container context), this doesn't actually expose the specified directory inside the container.

You likely have to add `-m /mnt/hdd/ffsend:/mnt/hdd/ffsend` to your command in order to mount the directory from the host system into the container. Note that you can specify a different path inside the container, such as `/files` if you so desire.

**Comment by sysoppl** [comment]
Oh, that was really stupid mistake I made. I really forgot to mount volume, my fault, sorry.

```
sudo docker create --name send \
  -e 'NODE_ENV=production' \
  -e 'PORT=1.2.3.4:3044:1443' \
  -e 'REDIS_HOST=1.2.3.4' \
  -e 'BASE_URL=https://url.com' \
  
  -v /mnt/hdd/ffsend:/mnt/hdd/ffsend \
  
  -e 'FILE_DIR=/mnt/hdd/send_data' \
  -e 'MAX_FILE_SIZE=10737420000' \
  -e 'MAX_EXPIRE_SECONDS=604800' \
  registry.gitlab.com/timvisee/send:latest && sudo docker start send
  ```
  seems to work. Thanks!
