### ISSUE TITLE
Doesn't download via download managers?

### ISSUE THREAD

**Issue by sharunkumar** [timvisee/send#30]
I tried downloading a file and it always download via chrome, instead of IDM which I have installed. Manually transferring the download to IDM doesn't seem to work either (maybe because of download count limit which was set to 1)

**Comment by timvisee** [comment]
I'm afraid this doesn't work.

Normally, you'll download a file through a direct URL which is passed to your download manager. With Send this works a little different in order to implement end-to-end encryption. Send downloads the encrypted file on your client, decrypts it with JavaScript running on the Send page, and saves the file. In other words, there's no direct link to download the file.

I don't think this is something we can improve upon without breaking end-to-end encryption. I'm sorry.
