### ISSUE TITLE
Downloading multiple files ZIP issue for smart-phones and non-tech peoples

### ISSUE THREAD

**Issue by maskmanlucifer** [timvisee/send#54]
Problem :
For now if i am sending more than one files through one link.
Then the downloaded folder will be zipped.
But if we consider all the scenario's like --

Non-tech user -- Not much experienced with zip/unzip folder,files.
Smart phone user -- Most of the unzipping solutions start with downloading files app.
From my experience most of the users share files on smart phones ( I am college student and quite often i send assignments , or some xyz pdf's to my friends on whatsapp).
Here "send" makes sharing multiple files easier by sharing only a link to all friends but if they will be on smart phones
then this will be painful task to get real files from downloaded zipped folder.

Possible Solution :
There can be a download icon ahead of each file on download page along with a download all button at the bottom.
So that Instead of downloading a zip folder a user can download pdf's seprately.

Now for lesser number of files above solution is quite good bcoz i'll rather click few icons to download pdf's
Rather than downloading zipped folder and extracting content from that folder.
For large number of files both clicking icons multiple times and unzipping folder will take same effort.
One more thing is giving icon ahead of each file gives a sense of selectivity like say i combined 4 files intended to be downloaded by 4 different users then they can download which pdf they want not whole folder.

**Comment by timvisee** [comment]
_Via https://github.com/timvisee/send/issues/21#issuecomment-898452836_

---

I'd definitely like that, but: this is currently hard to implement, and would require significant file handling/cryptography changes.

The current implementation (with a ZIP archive) was likely chosen because it was easy to implement on top of the single-file upload system.

There are some other problems when implementing such a system:

- Browsers don't properly support initiating multiple downloads
- Download limits are weird with multiple files

A nice middle ground could be to handle ZIP extracting within the browser itself, though I don't know how good such thing will work.

I don't want to go through the trouble to implement this because I sadly don't have time for it.

**Comment by timvisee** [comment]
Closing this because I won't be implementing this due to lack of time and limited browser support.

Feel free to open it again if new ideas arise, or if someone wants to work on this.

**Comment by schlagmichdoch** [comment]
@timvisee We could reopen this and use the native navigator.share() method:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#sharing_files

We would probably need to limit this in size this the files would need to be downloaded to RAM first.
